language: go
sudo: required

go:
  - 1.7

script:
  - make build_travis_aci

after_success:
  - mv redis.aci redis-latest-linux-amd64.aci
  # pull unixvoid gpg keys
  - curl -d sec=$BINDER_SEC -d key=unixvoid.pub https://cryo.unixvoid.com/getfile --output unixvoid.pub
  - curl -d sec=$BINDER_SEC -d key=unixvoid.sec https://cryo.unixvoid.com/getfile --output unixvoid.sec
  # sign aci
  - cp deps/sign.sh . && chmod +x sign.sh
  - ./sign.sh $GPG_SEC
  # upload binder aci image
  - curl -i --form sec=$BINDER_SEC --form file=@redis-latest-linux-amd64.aci --form path=rkt/redis/ https://cryo.unixvoid.com/upload
  - curl -i --form sec=$BINDER_SEC --form file=@redis-latest-linux-amd64.aci.asc --form path=rkt/redis/ https://cryo.unixvoid.com/upload
